name: Build Launcher

on:
  workflow_dispatch:
  push:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  linux:
    strategy:
      matrix:
        os: [ubuntu-22.04] # , ubuntu-20.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
     - name: Checkout repo
       uses: actions/checkout@v3
       with:
         repository: id-Software/quake2-rerelease-dll
         ref: main
         fetch-depth: 0

     - name: Install .NET Core
       uses: actions/setup-dotnet@v3
       with:
          dotnet-version: 7.x

     - name: Install dependencies
       run: |
          sudo apt-get update -qy
          sudo apt-get install -qy libsdl2-dev libfmt-dev libjsoncpp-dev

     - name: Publish Launcher
       run: |
         cd rerelease
         ls -al
         dotnet publish -nologo -c Release -r linux-x64

      #- name: Upload Mesen
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: Launcher
      #    path: launcher.exe
